version: "3.4"

services:

  api:
    container_name: "api"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - 5000:5000

  client:
    container_name: "client"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - ./client:/app
    restart: unless-stopped
    ports:
      - "5173:5173"




